INSERT INTO work_companies (work_company_id, company_name, chairman_id)
VALUES
  (1, 'Tech Solutions', 1),
  (2, 'Green Energy Corp', 2),
  (3, 'Innovatech', 3),
  (4, 'Blue Horizon', 4),
  (5, 'Quantum Industries', 5),
  (6, 'Future Vision', 6),
  (7, 'EcoBuild', 7),
  (8, 'Global Dynamics', 8),
  (9, 'Cybernetics Ltd', 9),
  (10, 'AlphaSoft', 10),
  (11, 'BioHealth Inc.', 11),
  (12, 'NextGen Solutions', 12),
  (13, 'Renewable Resources', 13),
  (14, 'Infinity Labs', 14),
  (15, 'Vertex Technologies', 15),
  (16, 'SkyNet Systems', 16),
  (17, 'Pioneer Enterprises', 17),
  (18, 'EverGreen', 18),
  (19, 'Stellar Innovations', 19),
  (20, 'Synergy Group', 20),
  (21, 'Elemental Industries', 21),
  (22, 'AstraTech', 22),
  (23, 'OmniCorp', 23),
  (24, 'Cosmos Enterprises', 24),
  (25, 'Zenith Corporation', 25);